### ISSUE TITLE
unc0ver still UNSUPPORTED while Fugu14 installed

### ISSUE THREAD

**Issue by PoopickerDowsion** [LinusHenze/Fugu14#51]
Device: iPhone 12 ProMax
OS version:14.5.1

Tried several times, also have wiped all data and re-jailbreak.

Nothing changed.

Pics listed below:

![14](https://user-images.githubusercontent.com/91650603/138760298-0b5a7816-c234-4cea-b49b-c36c2258a547.png)
![13](https://user-images.githubusercontent.com/91650603/138760300-f72333c9-da11-4633-838e-5be8448b6099.png)
![15](https://user-images.githubusercontent.com/91650603/138760489-986650ab-cdd7-4be3-b76b-e7b389ddd89e.jpg)

**Comment by XGsGorila** [comment]
did you solve it?

**Comment by ak1878** [comment]
FIX:
This happens to me every few months and it took me forever to figure out why it says unsupported but this method always works. Search Uncover IPA on google using your iphone and download the latest link from the first search result which is from the uncover website (on ios). Then, open altstore and press the add symbol on the top left, and open your ios files and choose the ipa that you just downloaded. Then it will take you through the usual process and you will be able to jailbreak it without a problem.

Overall, uncover is unsupported because you have to download the latest ipa/ the one that is being used is too old. Idk much about what an ipa is but have used uncover for years and i always have to do this every once in a while when uncover becomes unsupported. I have an iphone 11 pro max with the latest update.
